import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import MobileNav from "./ui/navigation/mobilenav";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({subsets: ["latin"], weight: ["400"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={poppins.className}>
        <div className="block sm:hidden"> <MobileNav /> </div>
          <div className="hidden sm:block"><Header /></div>
          
          {children}
        </body>
    </html>
  );
}
